### ISSUE TITLE
ModuleNotFoundError: No module named 'import_exporthome'

### ISSUE THREAD

**Issue by AlcindoSchleder** [django-import-export/django-import-export#1004]
I am install django-import-export but when execute runserver I receive this error:
```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/python/apis/icity-tax/venv/lib64/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'import_exporthome'
```

**Comment by andrewgy8** [comment]
Its hard to say without seeing what your code looks like, but it seems like you might have your settings.INSTALLED_APPS configured incorrectly. Can you include your settings file?

**Comment by AlcindoSchleder** [comment]
I really didn't realize the error in the settings.py file. The module was related but incorrectly.
Thanks for the clarification.
