### ISSUE TITLE
Handling many to many import

### ISSUE THREAD

**Issue by grwhumphries** [django-import-export/django-import-export#1052]
I have a many to many field I want to import, but can't get past the error:

```
Line number: 1 - __str__ returned non-string (type NoneType)
None, 1, test, 2019-12-22, 19.0029300000, -109.2234500000, http://www.test.com, 3, None, None, 1
Traceback (most recent call last):
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\import_export\resources.py", line 500, in import_row
diff = self.get_diff_class()(self, original, new)
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\import_export\resources.py", line 167, in __init__
self.left = self._export_resource_fields(resource, instance)
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\import_export\resources.py", line 188, in _export_resource_fields
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\import_export\resources.py", line 188, in <listcomp>
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\import_export\resources.py", line 673, in export_field
return field.export(obj)
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\import_export\fields.py", line 127, in export
value = self.get_value(obj)
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\import_export\fields.py", line 90, in get_value
value = getattr(value, attr, None)
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\django\db\models\fields\related_descriptors.py", line 527, in __get__
return self.related_manager_cls(instance)
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\django\db\models\fields\related_descriptors.py", line 840, in __init__
(instance, self.pk_field_names[self.source_field_name]))
File "C:\Anaconda3\envs\biodiversityAQ\lib\site-packages\django\db\models\base.py", line 519, in __repr__
return '<%s: %s>' % (self.__class__.__name__, self)
TypeError: __str__ returned non-string (type NoneType)
```

I've seen that there are issues dealing with many to many fields - has this been resolved at all?

**Comment by matthewhegarty** [comment]
Did you try defining a [dehydrated method](https://django-import-export.readthedocs.io/en/latest/getting_started.html#advanced-data-manipulation)?

It might help you get past the point where the error is occurring ([here](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L675)).

**Comment by matthewhegarty** [comment]
Closing due to no further input.
