### ISSUE TITLE
Admin import action - TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by aerospatiale** [django-import-export/django-import-export#1096]
I have a fairly basic setup that appears to be failing on clicking the Import action from /admin. 

admin.py:
```
from django.contrib import admin
from import_export import resources
from import_export.admin import ImportMixin

class MarketDataResource(resources.ModelResource):
    class Meta:
        model = MarketData


@admin.register(MarketData)
class MarketDataAdmin(ImportMixin, admin.ModelAdmin):
    resource_class = 'MarketDataResource'
```

models.py:
```
from django.db import models

class MarketData(models.model):

    name = models.CharField('Market data stream name', max_length=100)

    def __str__(self):
        return self.name
```

```
django_1              | 172.22.0.1 - - [10/Mar/2020 12:29:03] "GET /admin/users/marketdata/import/ HTTP/1.1" 500 -
django_1              | Traceback (most recent call last):
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
django_1              |     return self.application(environ, start_response)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/wsgi.py", line 141, in __call__
django_1              |     response = self.get_response(request)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 75, in get_response
django_1              |     response = self._middleware_chain(request)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 36, in inner
django_1              |     response = response_for_exception(request, exc)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 90, in response_for_exception
django_1              |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
django_1              |     return debug.technical_500_response(request, *exc_info)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
django_1              |     six.reraise(exc_type, exc_value, tb)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/six.py", line 702, in reraise
django_1              |     raise value.with_traceback(tb)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
django_1              |     response = get_response(request)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
django_1              |     response = self.process_exception_by_middleware(e, request)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
django_1              |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1              |   File "/usr/lib/python3.7/contextlib.py", line 74, in inner
django_1              |     return func(*args, **kwds)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
django_1              |     response = view_func(request, *args, **kwargs)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
django_1              |     response = view_func(request, *args, **kwargs)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/sites.py", line 223, in inner
django_1              |     return view(request, *args, **kwargs)
django_1              |   File "/usr/local/lib/python3.7/dist-packages/import_export/admin.py", line 327, in import_action
django_1              |     resource = self.get_import_resource_class()(**res_kwargs)
django_1              | TypeError: 'str' object is not callable
```

Anyone happen to have any clues on how to fix this by any chance?

Using version 2.0.2.

**Comment by aerospatiale** [comment]
`resource_class = 'MarketDataResource'` -> `resource_class = MarketDataResource`
