### ISSUE TITLE
Indentation error on version 1.2.0

### ISSUE THREAD

**Issue by webmarek** [django-import-export/django-import-export#1166]
**Describe the bug**
for version 1.2.0 such an error occurs when i run `python manage.py collectstatic`

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mors/.virtualenvs/nest-dev/lib/python3.6/site-packages/import_export/admin.py", line 143
    def process_import(self, request, *args, **kwargs):

```

**To Reproduce**
 just install it (django-import-export v 1.2.0 ) with django 1.8.4  and run  `python manage.py collectstatic`

when I went to specified line in specified file (`site-packages/import_export/admin.py`, line 143)
there was indentation of two tabs. Easy to fix, I guess :)

**Versions (please complete the following information):**
 - Django Import Export:  1.2
 - Python 3.6, 3.7
 - Django  1.8.4

**Expected behavior**
just remove the double tab
![image](https://user-images.githubusercontent.com/30749302/88281328-c30ad480-cce7-11ea-9253-bf2ee47930aa.png)

**Comment by andrewgy8** [comment]
Very Strange. I just checked version 1.2.0's changelog, and I can not see any changes on [line 143](https://github.com/django-import-export/django-import-export/compare/1.1.0...1.2.0#diff-1665e9fd887fef3df6a798903a398dbfL143) compared to the previous version. Can you try running another version of import-export and see if it works?

**Comment by andrewgy8** [comment]
Closing this for now, unless we hear any more reports
