### ISSUE TITLE
Excel File .xlsx Skipping the values of ManyToManyField

### ISSUE THREAD

**Issue by alexavenger** [django-import-export/django-import-export#1169]
**Describe the bug**
When importing excel file .xlsx with ManyToManyField is importing the values blank.
I've replicated on your Test App using your books-sample

**To Reproduce**
1. Open file "books-sample.csv" with Excel.
2. Split the csv in excel columns and save it as .xlsx 
3. Go to Admin site and open Book model.
4. Click on  import and select the .xlsx file

**Versions (please complete the following information):**
 - Django Import Export: 2.3
 - Python 3.7
 - Django 3.0.8

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47525730/88811142-7f680d00-d1b6-11ea-9819-70ee50f5b649.png)

**Comment by matthewhegarty** [comment]
I added a comment to the [SO post](https://stackoverflow.com/questions/63129282/import-m2m-empty-values-imported).  Import of m2m fields (in xlsx) worked fine for me using the example in the post.

If you still think this is an issue, please post examples of your code and an example of the file.

**Comment by alexavenger** [comment]
Here the excel I'm trying to import. 
[book_sampl_xlsx.xlsx](https://github.com/django-import-export/django-import-export/files/4995409/book_sampl_xlsx.xlsx)

The code is the one using in the Test Book App. 
Not sure if it's a problem of Excel System Configuration like separators...

**Comment by matthewhegarty** [comment]
That file imports fine for me.  What does your `Resource` look like?  You will need to define the field and widget (as mentioned in the SO post):

Update [admin.py](https://github.com/django-import-export/django-import-export/blob/master/tests/core/admin.py#L16)

```python
class BookResource(ModelResource):
    categories = fields.Field(
        attribute='categories',
        widget=widgets.ManyToManyWidget(Category, field='name',
                                        separator='|')
    )

    class Meta:
        model = Book
```

**Comment by alexavenger** [comment]
The file imports fine with all categories? 

In my case that column is blank when I see the previous details of the import. And when import is it blank.
![image](https://user-images.githubusercontent.com/47525730/88817167-77f83200-d1bd-11ea-8374-996a29024344.png)

This is how it looks like my resource. I think is the same but just in case.

```
class BookResource(ModelResource):
    categories = fields.Field(
        attribute='categories',
        widget=widgets.ManyToManyWidget(Category, field='name',
                                        separator='|')
    )

    class Meta:
        model = Book
```

**Comment by alexavenger** [comment]
See a video of what I do. To replicate the issue. :( Just in case you don't belive me  ;)
[Select book to change _ Django site admin - Google Chrome 2020-07-29 17-06-51.zip](https://github.com/django-import-export/django-import-export/files/4995638/Select.book.to.change._.Django.site.admin.-.Google.Chrome.2020-07-29.17-06-51.zip)

**Comment by matthewhegarty** [comment]
I assume you have run all [migrations and imported test data](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app).

**Comment by alexavenger** [comment]
I followed all the steps detailed. The only except I did was on this: I deleted this part from 0004_bookwithchapters.py

 ```
 pg_only_operations = [
        migrations.CreateModel(
            name='BookWithChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book name')),
                ('chapters', chapters_field),
                ('data', data_field)
            ],
        ),
    ]
```


As it was delivering this error when MakingMigrations

Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 87, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.load_disk()
  File "/home/alex_anadon/.local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 108, in load_disk
    migration_module = import_module(migration_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/alex_/Documents/python_projects/django-import-export/tests/core/migrations/0004_bookwithchapters.py", line 17, in <module>
    class Migration(migrations.Migration):
  File "/mnt/c/Users/alex_/Documents/python_projects/django-import-export/tests/core/migrations/0004_bookwithchapters.py", line 32, in Migration
    ('data', data_field)
NameError: name 'data_field' is not defined

**Comment by alexavenger** [comment]
the thing is that when I use your csv it works perfectly.

**Comment by alexavenger** [comment]
I think is something with the System Configuration. Regarding List Separators and regional configuration. Explained here: https://harvestmedia.zendesk.com/hc/en-us/articles/360023978031-Opening-Excel-files-with-the-correct-CSV-list-separator

¿Could be?

**Comment by matthewhegarty** [comment]
I suggest try to read the file directly using [tablib](https://tablib.readthedocs.io/en/stable/tutorial/#importing-data) and see if that works.

**Comment by alexavenger** [comment]
Yes, Tablib is having the same issue.
Basically is what I said, the local system configuration in tablib is different from the one I have. 
https://stackoverflow.com/questions/7751157/python-csv-list-separator-based-on-regional-settings

 I see you're investigating about pyexcel https://github.com/django-import-export/django-import-export/issues/1164  maybe that fix this..

You can close this if you want.

Thank you for your help!
