### ISSUE TITLE
Getting timeout when trying to import xlsx

### ISSUE THREAD

**Issue by franhace** [django-import-export/django-import-export#1171]
**Describe the bug**
I'm trying to import a file with a single row, besides the column names, it used to work correctly but now I'm getting a timeout error. 
Console outputs this:
```(0.177) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.179) SELECT `regions`.`region_id`, `regions`.`country_id`, `regions`.`name` FROM `regions` WHERE `regions`.`region_id` = 196; args=(196,)
(0.181) SELECT `senders`.`sender_id`, `senders`.`name` FROM `senders` WHERE `senders`.`sender_id` = 54; args=(54,)
(0.171) RELEASE SAVEPOINT `s139846053046016_x3`; args=None
```

**Versions (please complete the following information):**
 - Django Import Export: [2.2.0]
 - Python [3.6.4]
 - Django [2.2]

Getting this error also:
```
Exception while resolving variable 'confirm_form' in template 'admin/import_export/import.html'.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
current = current[bit]
File "/usr/local/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
raise KeyError(key)
KeyError: 'confirm_form'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'confirm_form'
```

**Comment by andrewgy8** [comment]
> it used to work correctly

Was that with another version of django/import-export/python?

**Comment by tanoabeleyra** [comment]
The same started happening to me too since version **2.2.0**, but in my case when exporting a CSV.
The weird thing is that it only happens when doing the export via the admin panel. It works fine when using `ModelResource.export()`

**Comment by matthewhegarty** [comment]
Could it be related to [this change](https://github.com/django-import-export/django-import-export/pull/1185/files) in v2.1.0 ?

**Comment by matthewhegarty** [comment]
@franhace Are you able to confirm if this is still happening in v2.5.0?

**Comment by 4bo** [comment]
same problem with v2.5.0

**Comment by matthewhegarty** [comment]
Can you help us out with steps to reproduce?  What exact error are you seeing?  Have you overridden any code or added any customisations?  What do your Resources look like?

**Comment by matthewhegarty** [comment]
Closing due to inactivity
