### ISSUE TITLE
Import with connected models

### ISSUE THREAD

**Issue by ayushbisht2001** [django-import-export/django-import-export#1297]
```python 
Line number: 1 - PatientCovidTest matching query does not exist.
Seema , 99xx-xx-99, 2021-04-27 00:00:00, 30, F, Okhali Sirot Bageshwar , S, A, A, so, GTR, 1, 1, 1
Traceback (most recent call last):
File "C:\Users\hp\.virtualenvs\covid_backend-vGvuVyo4\lib\site-packages\import_export\resources.py", line 658, in import_row
self.import_obj(instance, row, dry_run) 

File "C:\Users\hp\.virtualenvs\covid_backend-vGvuVyo4\lib\site-packages\import_export\resources.py", line 512, in import_obj
self.import_field(field, obj, data)

File "C:\Users\hp\.virtualenvs\covid_backend-vGvuVyo4\lib\site-packages\import_export\resources.py", line 495, in import_field
field.save(obj, data, is_m2m)

File "C:\Users\hp\.virtualenvs\covid_backend-vGvuVyo4\lib\site-packages\import_export\fields.py", line 110, in save
cleaned = self.clean(data)

File "C:\Users\hp\.virtualenvs\covid_backend-vGvuVyo4\lib\site-packages\import_export\fields.py", line 66, in clean
value = self.widget.clean(value, row=data)

File "C:\Users\hp\.virtualenvs\covid_backend-vGvuVyo4\lib\site-packages\import_export\widgets.py", line 396, in clean
return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})

File "C:\Users\hp\.virtualenvs\covid_backend-vGvuVyo4\lib\site-packages\django\db\models\query.py", line 429, in get
raise self.model.DoesNotExist(
patient.models.PatientCovidTest.DoesNotExist: PatientCovidTest matching query does not exist. 
```
 

name | contact_number | admitted_on | age | gender | address | covid_status | health_condition | patient_status | remark | covid_facility | is_tested | test_type | result
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

I want to import the above table into my database. The last 3 attributes belongs to different model which is linked to  main model through OneToOne relation. 

I have created Foreign key widget field for the last 3 attributes and included them in the fields also.
I guess the above error , comes when someone tries to get the models with some data which actually doesn't exits. 
is there any way to do this thing, please do reply fast it's urgent.

**Comment by ayushbisht2001** [comment]
@matthewhegarty, can u please help me, its urgent
