### ISSUE TITLE
Export Json ValueError: Circular reference detected

### ISSUE THREAD

**Issue by JV-conseil** [django-import-export/django-import-export#1303]
**Describe the bug**
While opting for `json` format export, the export does not go through and ends abruptly with a `ValueError: Circular reference detected` error message.

**To Reproduce**
\-

**Versions (please complete the following information):**
 - Django Import Export: 2.5.0
 - Python 3.8.11
 - Django 3.2.5

**Expected behavior**
Download of a `json` dump file.

**Screenshots**
\-

**Additional context**
```bash
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/import_export/admin.py", line 479, in export_action
    export_data = self.get_export_data(file_format, queryset, request=request)
  File "~/GitHub/sdurioanalytics/sdurioanalytics/core/admin.py", line 163, in get_export_data
    export_data = file_format.export_data(data)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/import_export/formats/base_formats.py", line 88, in export_data
    return dataset.export(self.get_title(), **kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/tablib/core.py", line 427, in export
    return fmt.export_set(self, **kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/tablib/formats/_json.py", line 26, in export_set
    return json.dumps(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

**Hypothesis**

We use pretty heterogeneous and challenging field types for `json` dump like `IntegerRangeField` or `MoneyField`.

```py
class Data(models.Model):
    publication_date = models.DateTimeField(null=True, default=None, blank=True)
    deadlines = ArrayField(models.DateTimeField(blank=True, default=None), default=list, blank=True)
    budget = MoneyField(null=True, default=None, blank=True, max_digits=12, decimal_places=2, default_currency='EUR')
    tags = ArrayField(ArrayField(models.CharField(max_length=255, blank=True)), default=list, blank=True)
    range = IntegerRangeField(null=True, default=None, blank=True)
    ...
```

We use our own `cls` subclassed from `DjangoJSONEncoder` when running `json.dumps({'data': data}, ensure_ascii=False, cls=GenericJSONEncoder)`.

Is there a way to inject our customised `cls` by subclassing `file_format.export_data()`? 

```py
def get_export_data(self, file_format, queryset, *args, **kwargs):
	"""
	Returns file_format representation for given queryset.
	"""
	request = kwargs.pop("request")
	if not self.has_export_permission(request):
		raise PermissionDenied

	resource_class = self.get_export_resource_class()
	data = resource_class(**self.get_export_resource_kwargs(request)).export(queryset, *args, **kwargs)
	export_data = file_format.export_data(data)
	return export_data
```

**Comment by bmihelac** [comment]
Hello @JV-conseil,

Using a custom JSON encoder is not currently supported; django-import-export uses what 
[tablib](https://github.com/jazzband/tablib) provides. 

It should not be complicated to create your own format. See:

https://github.com/django-import-export/django-import-export/blob/main/import_export/formats/base_formats.py

As this could be useful to more users, I would be happy to merge a PR that offers this functionality.

**Comment by TonisPiip** [comment]
Yeah, this a massive :-1:. From looking at that code I'm not seeing a simple way to inject the cls, or how to register a new type. :(

**Comment by matthewhegarty** [comment]
Can you be more specific as to what you are trying to do?  What have you tried etc?  There are [several methods](https://django-import-export.readthedocs.io/en/latest/api_resources.html) that you can override to customize the code
