### ISSUE TITLE
Exception while resolving variable 'subtitle' in template 'admin/import_export/export.html'

### ISSUE THREAD

**Issue by hsb-tonmoy** [django-import-export/django-import-export#1453]
**Describe the bug**
Request processes for about 30 seconds and then produces Secure Connection Failed error when exporting data. Heroku logs:

```
Exception while resolving variable 'subtitle' in template 'admin/import_export/export.html'.
2022-06-24T13:38:32.984664+00:00 app[web.1]: Traceback (most recent call last):
2022-06-24T13:38:32.984683+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 862, in _resolve_lookup
2022-06-24T13:38:32.984683+00:00 app[web.1]: current = current[bit]
2022-06-24T13:38:32.984683+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/template/context.py", line 83, in __getitem__
2022-06-24T13:38:32.984684+00:00 app[web.1]: raise KeyError(key)
2022-06-24T13:38:32.984684+00:00 app[web.1]: KeyError: 'subtitle'
2022-06-24T13:38:32.984684+00:00 app[web.1]:
2022-06-24T13:38:32.984685+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-06-24T13:38:32.984685+00:00 app[web.1]:
2022-06-24T13:38:32.984686+00:00 app[web.1]: Traceback (most recent call last):
2022-06-24T13:38:32.984686+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 868, in _resolve_lookup
2022-06-24T13:38:32.984686+00:00 app[web.1]: if isinstance(current, BaseContext) and getattr(type(current), bit):
2022-06-24T13:38:32.984686+00:00 app[web.1]: AttributeError: type object 'RequestContext' has no attribute 'subtitle'
2022-06-24T13:38:32.984687+00:00 app[web.1]:
2022-06-24T13:38:32.984687+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-06-24T13:38:32.984687+00:00 app[web.1]:
2022-06-24T13:38:32.984687+00:00 app[web.1]: Traceback (most recent call last):
2022-06-24T13:38:32.984687+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 876, in _resolve_lookup
2022-06-24T13:38:32.984687+00:00 app[web.1]: current = current[int(bit)]
2022-06-24T13:38:32.984688+00:00 app[web.1]: ValueError: invalid literal for int() with base 10: 'subtitle'
2022-06-24T13:38:32.984688+00:00 app[web.1]:
2022-06-24T13:38:32.984689+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-06-24T13:38:32.984689+00:00 app[web.1]:
2022-06-24T13:38:32.984689+00:00 app[web.1]: Traceback (most recent call last):
2022-06-24T13:38:32.984689+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/template/base.py", line 881, in _resolve_lookup
2022-06-24T13:38:32.984689+00:00 app[web.1]: raise VariableDoesNotExist("Failed lookup for key "
2022-06-24T13:38:32.984741+00:00 app[web.1]: django.template.base.VariableDoesNotExist: Failed lookup for key [subtitle]
```

**Versions (please complete the following information):**
 - Django Import Export: [2.8.0]
 - Python [3.9]
 - Django [4.0.1]

**Expected behavior**
I expected a csv file to be generated.

**Screenshots**

![image](https://user-images.githubusercontent.com/35843150/175556818-52723ec9-0bbb-485d-8c89-62c85d140ba0.png)

**Comment by matthewhegarty** [comment]
Likely your request is timing out due to a long running process, checkout the [celery](https://django-import-export.readthedocs.io/en/latest/celery.html) implementation for long running processes.
