### ISSUE TITLE
AttributeError when 'change_list_template' is a "@property"-decorated method

### ISSUE THREAD

**Issue by ShaheedHaque** [django-import-export/django-import-export#1521]
**Describe the bug**

I use https://github.com/django-polymorphic, which has Admin support including a `change_list_template` which is implemented using `@property`, [as you can see](https://github.com/django-polymorphic/django-polymorphic/blob/bd5faf0c829f87dc6fcc42c6bfbb689d665a5bf4/polymorphic/admin/parentadmin.py#L363). Since #1483 (IIUC) this causes this exception:

```
Traceback (most recent call last):
...
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/sites.py", line 149, in register
    self._registry[model] = admin_class(model, self)
  File "/usr/local/lib/python3.10/dist-packages/import_export/admin.py", line 49, in __init__
    self.change_list_template = getattr(
AttributeError: can't set attribute 'change_list_template'
```

**To Reproduce**
1. IIUC, any project using django-import-export and django-polymorphic will encounter this issue.
2. See error when trying to start the server.

 - Django Import Export: 3.0.1
 - Python: 3.10, but probably any other would show the issue
 - Django: 4.0.6 or 4.1

**Expected behavior**
Not sure, but certainly no exception.

**Additional context**
I'm afraid I'm not very familiar with the Django Admin, so I'm not terribly clear what to suggest as the desired behaviour other than not to cause an error.

**Comment by matthewhegarty** [comment]
Possibly related to #1514

**Comment by matthewhegarty** [comment]
Thanks for raising this.  I just installed django-polymorphic and couldn't reproduce.  If you could reproduce this issue using the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app), that would be a great help.  Failing that, can you give us any additional information to reproduce the issue.

**Comment by ShaheedHaque** [comment]
@matthewhegarty Thanks for looking. I am able to repro the problem using the example app as follows:

1. Install django-polymorphic.
2. Verify that the example app starts up, i.e. `./manage.py runserver` as usual.
3. Apply the [polymorphic.txt](https://github.com/django-import-export/django-import-export/files/10164860/polymorphic.txt) patch to the example app. Something like this:
   ```
   $ patch -p2 < polymorphic.txt
   ```
5. Verify that the example app fails to start up:

```
$ ./manage.py runserver
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.10/dist-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/dist-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/main/srhaque/kdedev/django-import-export/tests/core/admin.py", line 95, in <module>
    admin.site.register(CompanyPostalDetail, CompanyPostalDetailAdmin)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/admin/sites.py", line 149, in register
    self._registry[model] = admin_class(model, self)
  File "/main/srhaque/kdedev/django-import-export/tests/./../import_export/admin.py", line 49, in __init__
    self.change_list_template = getattr(
AttributeError: can't set attribute 'change_list_template'
```

**Comment by ShaheedHaque** [comment]
As a minimum, perhaps catch the exception? I know that sounds like a bit of
a hack but...

**Comment by matthewhegarty** [comment]
hi @ShaheedHaque I had another look, and have come up with the following

- The reason it doesn't work as it did in 2.x is because of the changes made in #1483, this was implemented so that import-export plays nicely with other plugins which define change list templates (ironically it has broken in this case).
- The issue we have is that `change_list_template` is a defined as a property in the polymorphic library, hence we cannot change that value and if we try to do so we get the error, so all we can do is catch that and continue.
- I have modified the log level from `exception` to `error` - I think this is valid - it is an unexpected error outside of our control, so we should log it.  If you don't want this in your logs you can configure the logging level for import-export in your application (i.e. set it to 'warning' level).
- To restore the 2.x changelist template, you can declare in your mixin:

```python
class CompanyPostalDetailAdmin(ImportExportMixin, poly_parentadmin.PolymorphicParentModelAdmin):
    change_list_template = 'admin/import_export/change_list_export.html'
```

I think this is a fair compromise between handling errors generated from integration alongside other libraries, and allowing flexibility for customisation.  

Please could you try the latest changes and let me know what you think.

**Comment by ShaheedHaque** [comment]
Please feel free to close this.

**Comment by matthewhegarty** [comment]
great - thanks Shaheed
