### ISSUE TITLE
ImportExportMixin not compatible with django-admin-sortable2

### ISSUE THREAD

**Issue by PetrDlouhy** [django-import-export/django-import-export#1525]
**Describe the bug**
When I update to djagno-import-export>=3.0.0 I got this errror:
```
Traceback (most recent call last):
  File "/home/petr/soubory/programovani/blenderkit/blenderhub_server/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/contrib/admin/__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/petr/soubory/programovani/blenderkit/blenderhub_server/blenderhub/apps/evaluation/admin.py", line 13, in <module>
    class RatingType(SortableAdminMixin, ImportExportMixin, admin.ModelAdmin):
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/contrib/admin/decorators.py", line 107, in _model_admin_wrapper
    admin_site.register(models, admin_class=admin_class)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/admin_tools_stats/app_label_renamer.py", line 76, in wrap
    return f(model, admin_class, **option)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 149, in register
    self._registry[model] = admin_class(model, self)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/adminsortable2/admin.py", line 108, in __init__
    super().__init__(model, admin_site)
  File "/home/petr/.cache/pypoetry/virtualenvs/blenderkit-server-eqrfB9dY-py3.10/lib/python3.10/site-packages/import_export/admin.py", line 49, in __init__
    self.change_list_template = getattr(
AttributeError: can't set attribute 'change_list_template'
````

**To Reproduce**
1. Write ModelAdmin class with both SortableAdminMixin and ImportExportMixin like this:
```python
class MyModelAdmin(ImportExportMixin, SortableAdminMixin, admin.ModelAdmin):
    ...
````
2. Execute `python manage.py runserver`

**Versions (please complete the following information):**
 - Django Import Export: [3.0.0, 3.0.1]
 - Python [3.10]
 - Django [4.0.8]

**Expected behavior**
Before 3.0.0 these mixins did work.

**Additional context**
This is probably connected with these issues and PRs: #1450, #1483

**Comment by matthewhegarty** [comment]
Hi Petr - please take a look at issue at issue #1521 which we've been working on today.  A fix has just gone into main which catches and logs 3rd party errors.

**Comment by matthewhegarty** [comment]
Looks like it is the same issue, where we cannot update `change_list_template` when adminsortable2 is present because it is [defined as a property](https://github.com/jrief/django-admin-sortable2/blob/7bb2640fb35939d52248756b089ae27241d313f4/adminsortable2/admin.py#L96).

**Comment by PetrDlouhy** [comment]
@matthewhegarty Yeah, seems to be working with @main.
