### ISSUE TITLE
XLSX export raises IllegalCharacterError

### ISSUE THREAD

**Issue by barsch** [django-import-export/django-import-export#2000]
**Describe the bug**

Exporting an object with a `TextField` containing "solarterrestrial" (unfortunately GitHub converts this character, see screenshot below how it looks for me) into a XLSX file raises a `IllegalCharacterError` - see traceback below. Exporting into CSV,  ODS or JSON works as it should. Duplicate of unsolved issue #1712.

![error](https://github.com/user-attachments/assets/38409d2b-fe25-4102-899c-4d1a23755f17)

```
Traceback (most recent call last):
  File "c:\Program Files\Python311\Lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\wsgi.py", line 124, in __call__
    response = self.get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\test\src\test\core\middleware.py", line 42, in __call__
    return self.get_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\test\src\test\core\middleware.py", line 54, in __call__
    response = self.get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\test\src\test\core\middleware.py", line 85, in __call__
    return self.get_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\test\src\test\core\middleware.py", line 170, in __call__
    return self.get_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\test\src\test\core\middleware.py", line 135, in __call__
    return self.get_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Workspace\test\src\test\core\middleware.py", line 193, in __call__
    response = self.get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\simple_history\middleware.py", line 41, in middleware
    return get_response(request)
           ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\allauth\account\middleware.py", line 36, in middleware
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\deprecation.py", line 129, in __call__
    response = response or self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 57, in inner
    response = response_for_exception(request, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\import_export\admin.py", line 773, in export_action
    return self._do_file_export(
           ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\import_export\admin.py", line 837, in _do_file_export
    export_data = self.get_export_data(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\import_export\admin.py", line 718, in get_export_data
    export_data = file_format.export_data(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\import_export\formats\base_formats.py", line 213, in export_data
    return super().export_data(dataset, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\import_export\formats\base_formats.py", line 91, in export_data
    return dataset.export(self.get_title(), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\tablib\core.py", line 434, in export
    return fmt.export_set(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\tablib\formats\_xlsx.py", line 60, in export_set
    cls.dset_sheet(dataset, ws, freeze_panes=freeze_panes, escape=escape)
  File "d:\Workspace\test\.venv\Lib\site-packages\tablib\formats\_xlsx.py", line 163, in dset_sheet
    cell.value = col
    ^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\openpyxl\cell\cell.py", line 218, in value
    self._bind_value(value)
  File "d:\Workspace\test\.venv\Lib\site-packages\openpyxl\cell\cell.py", line 197, in _bind_value
    value = self.check_string(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Workspace\test\.venv\Lib\site-packages\openpyxl\cell\cell.py", line 165, in check_string
    raise IllegalCharacterError(f"{value} cannot be used in worksheets.")
openpyxl.utils.exceptions.IllegalCharacterError: solar☻terrestrial cannot be used in worksheets.  
```

**To Reproduce**
  - create/use a model with a TextField
  - in Django Admin copy & paste "solarterrestrial" into the field above and save the object
  - click on "export" button in the ModelAdmin change form
  - chose "XLSX" and submit

**Versions**
 - Django Import Export: 4.2.1
 - Python 3.11.7
 - Django 5.1.3
 - openpyxl 3.1.5

**Expected behavior**
Just have these characters escaped or replaced and continue with the export. In best case have a message to the user about the replacement of some characters. (shameless copy from #1712)

Also see https://www.havnemark.dk/?p=185

**Additional context**
The actual string which fails in openpyxl's ```check_string``` is displayed below
```
Call Location:
  File "c:\Program Files\Python311\Lib\bdb.py", line 336, in set_trace
    sys.settrace(self.trace_dispatch)

> d:\workspace\test\.venv\lib\site-packages\openpyxl\cell\cell.py(165)check_string()
-> raise IllegalCharacterError(f"{value} cannot be used in worksheets.")
(Pdb) value
'solar\x02terrestrial'
```

**Comment by matthewhegarty** [comment]
Thanks for reporting.  I can reproduce this now with:

```python
>>> b1 = Book.objects.last()
>>> b1.name = 'Moon' + chr(11)
>>> b1.save()
```

Then export as 'xlsx' in Admin UI.

**Comment by matthewhegarty** [comment]
Associated issue on [tablib](https://github.com/jazzband/tablib/issues/370).

**Comment by barsch** [comment]
thanks for tackling this issue so fast!

I tested with ```IMPORT_EXPORT_ESCAPE_ILLEGAL_CHARS_ON_EXPORT``` on and off and both worked flawlessly in my project

I would suggest to improve upon the error message a bit - currently its just "Export failed due to IllegalCharacterError" which does not indicate where the illegal character can be found and can be troublesome while exporting multiple objects with various fields - I would suggest to include at least the object name/pk (maybe link it) - additional field name and character position would be even better

however I can happily life with the current implementation as I'll use the auto escape mechanism

thanks again!

**Comment by matthewhegarty** [comment]
Thanks for testing this and confirming.  

> I would suggest to improve upon the error message a bit 

Good call - although I'm always slightly nervous about reporting data from the row due to the risk of leaking sensitive information or even xss flaws.  The openpyxl library raises the original source of the error, so I compromised in logging that as an exception.  Does that help track down the source of the error?  I can't use object name or pk because the error is thrown from tablib, and doesn't have that information.

**Comment by barsch** [comment]
> Good call - although I'm always slightly nervous about reporting data from the row due to the risk of leaking sensitive information or even xss flaws. The openpyxl library raises the original source of the error, so I compromised in logging that as an exception. Does that help track down the source of the error? I can't use object name or pk because the error is thrown from tablib, and doesn't have that information.

yeah I wouldn't want the illegal string displayed itself - just the object name & field name of entries with an illegal character would be perfect - anyway, you know better than me what is possible and what not ...

ofc one could just check all fields against ```openpyxl.cell.cell.ILLEGAL_CHARACTERS_RE``` before sending data to tablib (only for XLSX export) - however its probably way to expensive ...

so like I said I'm fine as it is
