### ISSUE TITLE
ManyToManyWidget not ready to work with intermediary models

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#306]
`models.py`

```
class Case(Model):
    persons_involved = \
        ManyToManyField(
            Person,
            through=PersonInvolvement)
```

Two variants of `admin.py`:
this one breaks import ( #151  ):

```
class CaseResource(ModelResource):
    persons_involved = fields.Field(
        attribute='persons_involved',
        widget=ManyToManyWidget(Person, field='full_name'))
```

> Cannot set values on a ManyToManyField which specifies an intermediary model.  Use PersonInvolvement's Manager instead.

And if I use PersonInvolvement

```
class CaseResource(ModelResource):
    persons_involved = fields.Field(
        attribute='persons_involved',
        widget=ManyToManyWidget(PersonInvolvement, field='person__full_name'))
```

> Line number: 1 - 'Person' object has no attribute 'person__full_name'
> Traceback (most recent call last):
> File "import_export/resources.py", line 370, in import_data
> real_dry_run)
> File "import_export/resources.py", line 281, in get_diff
> v1 = self.export_field(field, original) if original else ""
> AttributeError: 'Person' object has no attribute 'person__full_name'

Obviously, if I use `field='full_name'` it can't find it on the `PersonInvolvement` model.

**Comment by int-ua** [comment]
Maybe it's a complete duplicate of 151, I'm just not sure.
