### ISSUE TITLE
Import fails with encoding issues....how to force utf-8 support ?

### ISSUE THREAD

**Issue by abadger1406** [django-import-export/django-import-export#307]
Trying to import large file with lots of European names...get following errors...

Line number: 136 - 'ascii' codec can't encode character u'\u2019' in position 18: ordinal not in range(128)
Traceback (most recent call last):
File "/home/Env/ap/local/lib/python2.7/site-packages/import_export/resources.py", line 367, in import_data
row_result.object_repr = force_text(instance)
File "/home/Env/ap/local/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 18: ordinal not in range(128)

Line number: 448 - 'ascii' codec can't encode character u'\u2019' in position 17: ordinal not in range(128)
Traceback (most recent call last):
File "/home/Env/ap/local/lib/python2.7/site-packages/import_export/resources.py", line 367, in import_data
row_result.object_repr = force_text(instance)
File "/home/Env/ap/local/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 17: ordinal not in range(128)

Line number: 1129 - 'ascii' codec can't encode character u'\u2019' in position 16: ordinal not in range(128)
Traceback (most recent call last):
File "/home/Env/ap/local/lib/python2.7/site-packages/import_export/resources.py", line 367, in import_data
row_result.object_repr = force_text(instance)
File "/home/Env/ap/local/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 16: ordinal not in range(128)

Line number: 1141 - 'ascii' codec can't encode character u'\u2019' in position 16: ordinal not in range(128)
Traceback (most recent call last):
File "/home/Env/ap/local/lib/python2.7/site-packages/import_export/resources.py", line 367, in import_data
row_result.object_repr = force_text(instance)
File "/home/Env/ap/local/lib/python2.7/site-packages/django/utils/encoding.py", line 94, in force_text
s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 16: ordinal not in range(128)

**Comment by abadger1406** [comment]
This post looks replated to this issue....justb unsure best way to fix.

http://stackoverflow.com/questions/24358361/removing-u2018-and-u2019-character

**Comment by abadger1406** [comment]
An example model might be:-

class Investor(models.Model):
      uid = models.IntegerField(primary_key=True, unique=True)
      name = models.TextField(max_length=100)
      email = models.EmailField()
      address = models.TextField()
  
      account_name = models.CharField(max_length=50, null=True, blank=True)
      account_bank = models.CharField(max_length=50, null=True, blank=True)
      account_account = models.CharField(max_length=50, null=True, blank=True)
      account_sort = models.CharField(max_length=50, null=True, blank=True)
      account_swift = models.CharField(max_length=50, null=True, blank=True)
      account_iban = models.CharField(max_length=50, null=True, blank=True)
  
      def __str__(self):
          return '%d - ' % (self.uid)

And then trying to import xx.csv:-

$ more xx.csv
id , name , email , address , account_name , account_bank , account_account , account_sort , account_swift , account_iban
22,erône,dave@test.org,Address,,,,,,



Gives this error:-


ine number: 1 - u"Column 'uid' not found in dataset. Available columns are: [u'id ', u' name ', u' email ', u' address ', u' account_name ', u' account_bank ', u' account_account ', u' account_sort ', u' account_swift ', u' account_iban']"
Traceback (most recent call last):
File "/home/Env/ap/local/lib/python2.7/site-packages/import_export/resources.py", line 342, in import_data
instance, new = self.get_or_init_instance(instance_loader, row)
File "/home/Env/ap/local/lib/python2.7/site-packages/import_export/resources.py", line 174, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
KeyError: u"Column 'uid' not found in dataset. Available columns are: [u'id ', u' name ', u' email ', u' address ', u' account_name ', u' account_bank ', u' account_account ', u' account_sort ', u' account_swift ', u' account_iban']"

**Comment by bmihelac** [comment]
looking at stack trace it looks like that your model ``__unicode__`` method does not returns unicode string

**Comment by bmihelac** [comment]
I'm closing this, please reopen if needed.
