### ISSUE TITLE
How do I assign a related object on import?

### ISSUE THREAD

**Issue by p3k** [django-import-export/django-import-export#319]
I am trying to add a new user when importing a user profile, the latter being an extension of Django’s user model, and thus to be assigned to the profile as a related object:

```python
class UserProfileResource(resources.ModelResource):

  def before_import(self, dataset, dry_run, **kwargs):
    if 'id' not in dataset.headers:
      dataset.insert_col(0, [''], 'id')
    data = dataset.dict[0]
    username = data['username']
    email = data['email']
    try:
      user = User.objects.get(username=username, email=email)
    except User.DoesNotExist:
      user = User.objects.create_user(username=username, email=email)
    dataset.append_col([user.id], 'user_id')
    print dataset
    super(UserProfileResource, self).before_import(dataset, dry_run, **kwargs)

  def before_save_instance(self, instance, dry_run, **kwargs):
    print instance.__dict__
    super(UserProfileResource, self).before_save_instance(instance, dry_run, **kwargs)

  class Meta:
    model = UserProfile
```

I am getting the new user instance in the data base as well as the additional column with the correct user ID in `before_import()` but in `before_save_instance()` the property `user_id` is None:

**print dataset:**
```
id|username|first_name|last_name|email       |building|apartment|user_id
--|--------|----------|---------|------------|--------|---------|-------
  |erster  |Erster    |Test     |erster@te.st|1.0     |123.0    |225    
```

**print instance.\__dict__:**
```
{'user_id': None, 'reset_date': None, '_django_version': '1.8.4', 'image': u'', '_state': <django.db.models.base.ModelState object at 0
x10ac414d0>, 'temp_password': u'', 'id': None}
```

As a result I get the following error after I submit the XLS in Django:

```
Line number: 1 - UserProfile has no user.
OrderedDict([('id', ''), (u'username', u'erster'), (u'first_name', u'Erster'), (u'last_name', u'Test'), (u'email', u'erster@te.st'), (u'building', 1.0), (u'apartment', 123.0), ('user_id', 225)])
Traceback (most recent call last):
File "/Users/tobi/.virtualenvs/infoboard/lib/python2.7/site-packages/import_export/resources.py", line 380, in import_data
row_result.object_repr = force_text(instance)
File "/Users/tobi/.virtualenvs/infoboard/lib/python2.7/site-packages/django/utils/encoding.py", line 92, in force_text
s = six.text_type(s)
RelatedObjectDoesNotExist: UserProfile has no user.
```
Any ideas?

**Comment by p3k** [comment]
OK, I now found out it might be a better idea to use the `init_instance()` method:

```python
class UserProfileResource(resources.ModelResource):

  def init_instance(self, data, *args, **kwargs):
    instance = super(UserProfileResource, self).init_instance(*args, **kwargs)
    user = User.objects.create_user(username=data['username'], email=data['email'])
    user.first_name = data['first_name']
    user.last_name = data['last_name']
    instance.user = user
    print instance.user.pk
    return instance
```

However, now I get this exception, although `instance.user.pk` is the actual ID of the new user object.

```
IntegrityError at /-/admin/auth/user/process_import/
UNIQUE constraint failed: api_userprofile.user_id
```

What am I doing wrong?

**Comment by p3k** [comment]
@bmihelac forgive me for bumping this; I could really need some help…

**Comment by p3k** [comment]
I now managed to implement the import of UserProfiles, reverting back to the `before_import()` method:

```python
class UserProfileResource(resources.ModelResource):

  def before_import(self, dataset, dry_run, *args, **kwargs):
    user_ids = []

    for data in dataset.dict:
      username = data['username']
      email = data['email']
      building = Building.objects.get(pk=data['building'])
      apartment = data['apartment']

      try:
        user = User.objects.get(username=username, email=email)
      except User.DoesNotExist:
        user = User.objects.create_user(username=username, email=email)
        user.first_name = data['first_name']
        user.last_name = data['last_name']
        user.save()

      try:
        location = Location.objects.get(user=user, building=building, apartment=apartment)
      except Location.DoesNotExist:
        location = Location(user=user, building=building, apartment=apartment)
        location.save()

      user_ids.append(user.id)

    dataset.insert_col(0, user_ids, 'user')
    return super(UserProfileResource, self).before_import(dataset, dry_run, *args, **kwargs)

  class Meta:
    model = UserProfile
    fields = ('user', 'username', 'first_name', 'last_name', 'email', 'building', 'apartment')
    import_id_fields = ('user',)
```

For the sake of completeness, here is also the UserProfile model:

```python
class UserProfile(models.Model):
  user = models.OneToOneField(User, primary_key=True)
  image = models.ImageField(upload_to='profiles/%Y/%m', blank=True, verbose_name='Bild')
  temp_password = models.CharField(u'Temporäres Kennwort', max_length=255, blank=True)
  reset_date = models.DateTimeField(u'Gültig bis', blank=True, null=True, help_text='')
```

**Comment by bmihelac** [comment]
@p3k  glad you make it work, here are my thoughts on this.

I would override ``get_or_init_instance`` method and get or initialize ``User`` object setting it as private attribute of ``UserProfile`` instance. 

Then ``import_obj`` would be overriden and if ``dry_run`` is ``False`` I would save user and assign it to current instance.

See https://django-import-export.readthedocs.org/en/latest/import_workflow.html for all hooks you can use when importing.

**Comment by Fastjur** [comment]
@bmihelac Could you help me out? I know your comment was in 2015, but I'm hoping you can still help me as I am clueless right now. I am having a similar issue. I have a bit more complex model, but I followed your advice. I have the following `get_or_init_instance`:

```python
class StudentResource(resources.ModelResource):
    def get_or_init_instance(self, instance_loader, row):
        print("=================")
        print(row)

        for key, value in row.items():
            print(key, value)

        initials = row['person__initials']  # TODO: Check if this is a tablib error with ufeff character (BOM)
        firstname = row['person__firstname']
        preposition = row['person__preposition']
        surname = row['person__surname']
        netid = row['person__netid']
        street_name = row['person__street_name']
        house_number = row['person__house_number']
        postcode = row['person__postcode']
        city = row['person__city']
        country = row['person__country']
        email = row['person__email']
        phone_mobile = row['person__phone_mobile']
        gender = row['person__gender']
        birthdate = row['person__birthdate']
        mail_announcements = row['person__mail_announcements']
        mail_company = row['person__mail_company']
        mail_education = row['person__mail_education']
        machazine = row['person__machazine']

        person = Person.objects.create(
            initials=initials,
            firstname=firstname,
            preposition=preposition,
            surname=surname,
            netid=netid,
            street_name=street_name,
            house_number=house_number,
            postcode=postcode,
            city=city,
            country=country,
            email=email,
            phone_mobile=phone_mobile,
            gender=gender,
            birthdate=dateutil.parser.parse(birthdate),
            mail_announcements=mail_announcements,
            mail_company=mail_company,
            mail_education=mail_education,
            machazine=machazine
        )

        print("PERSON ID", person.id)

        print("=================", flush=True)
        return super(StudentResource, self).get_or_init_instance(instance_loader, row)
        # TODO link student to person here

    def get_instance(self, instance_loader, row):
        try:
            params = {}
            for key in instance_loader.resource.get_import_id_fields():
                field = instance_loader.resource.fields[key]
                params[field.attribute] = field.clean(row)
            return self.get_queryset().get(**params)
        except Exception:
            return None

    class Meta:
        model = Student
        use_transactions = True
        fields = ('person__initials', 'person__firstname', 'person__preposition', 'person__surname', 'person__netid', 'student_number', 'person__street_name', 'person__house_number', 'person__postcode', 'person__city', 'person__country', 'person__email', 'person__phone_mobile', 'person__gender', 'person__birthdate', 'yearbook_permission', 'person__mail_announcements', 'person__mail_company', 'person__mail_education', 'person__machazine', 'first_year', 'study', 'emergency_phone', 'emergency_name')
```

The person gets created and gets an ID, but how do I link it to student? The relationship is as follows:

```python
class Student(models.Model):
...(omitted)
    person = models.OneToOneField(Person, primary_key=True, on_delete=models.CASCADE)
...(omitted)
```
