### ISSUE TITLE
Export XLS encoding problem 

### ISSUE THREAD

**Issue by daniele-sartiano** [django-import-export/django-import-export#428]
Hi, I have a problem with encoding:

> Internal Server Error: /administration/export/excel/
> Traceback (most recent call last):
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
>     return bound_func(*args, **kwargs)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
>     return view_func(request, *args, **kwargs)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
>     return func.__get__(self, type(self))(*args2, **kwargs2)
>   File "/project/biocare/clinicamobile/djangoRest/administration/views.py", line 50, in dispatch
>     return super(AdministrationWebPageView, self).dispatch(*args, **kwargs)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/project/biocare/clinicamobile/djangoRest/administration/views.py", line 212, in get
>     response = HttpResponse(dataset, content_type=content_type)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/http/response.py", line 320, in __init__
>     self.content = content
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/http/response.py", line 343, in content
>     value = self.make_bytes(value)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/http/response.py", line 283, in make_bytes
>     return force_bytes(value, self._charset)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/django/utils/encoding.py", line 151, in force_bytes
>     return six.text_type(s).encode(encoding, errors)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/tablib/core.py", line 239, in __unicode__
>     return '\n'.join(format_string.format(*row) for row in result)
>   File "/project/.envs/clinica/local/lib/python2.7/site-packages/tablib/core.py", line 239, in <genexpr>
>     return '\n'.join(format_string.format(*row) for row in result)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 98: ordinal not in range(128)

Is there a workaround to solve this problem?

**Comment by daniele-sartiano** [comment]
It was my error.
