### ISSUE TITLE
Can't import a recursive relationship

### ISSUE THREAD

**Issue by sglebs** [django-import-export/django-import-export#435]
I have an entity which is recursive:

```
class System(models.Model):
    name = models.CharField(max_length=60, null=False, blank=False, verbose_name ="sistema") #blank is for admin, null is for DB
    online_url = models.CharField(max_length=128, null=True, blank=True, verbose_name ="URL do sistema") #blank is for admin, null is for DB
    health_url = models.CharField(max_length=128, null=True, blank=True, verbose_name ="URL de ping") #blank is for admin, null is for DB
    health_regex = models.CharField(max_length=128, null=True, blank=True, verbose_name ="regex de aceite do ping") #blank is for admin, null is for DB
    health_result_expected = models.IntegerField(default=200, null=False, blank=False, verbose_name="HTTP Code esperado") #blank is for admin, null is for DB
    system = models.ForeignKey('self', verbose_name ="sistema pai", null=True, blank=True, related_name='systems') #blank is for admin, null is for DB
```

I am able to export this fine but on import I get errors:

```
System matching query does not exist.
0, Administração dos Usuários da Instituição, .*, 390, , , http://www2.tjal.jus.br/esajperfil/abrirAdministracaoDeUsuario.do, http://www2.tjal.jus.br/esajperfil/abrirAdministracaoDeUsuario.do, 200, 358, 880,200
Traceback (most recent call last):
File "/app/.heroku/python/lib/python2.7/site-packages/import_export/resources.py", line 426, in import_row
self.import_obj(instance, row, dry_run)
File "/app/.heroku/python/lib/python2.7/site-packages/import_export/resources.py", line 299, in import_obj
self.import_field(field, obj, data)
File "/app/.heroku/python/lib/python2.7/site-packages/import_export/resources.py", line 289, in import_field
field.save(obj, data)
File "/app/.heroku/python/lib/python2.7/site-packages/import_export/fields.py", line 112, in save
setattr(obj, attrs[-1], self.clean(data))
File "/app/.heroku/python/lib/python2.7/site-packages/import_export/fields.py", line 66, in clean
value = self.widget.clean(value)
File "/app/.heroku/python/lib/python2.7/site-packages/import_export/widgets.py", line 272, in clean
return self.model.objects.get(**{self.field: val}) if val else None
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
self.model._meta.object_name
DoesNotExist: System matching query does not exist.
```
I guess it would work if the import was all done in a transaction. Or if the IDs would be automagically transformed and the order of inserts would be computed.

Is there a way to make this work? Perhaps export in such an order so that the sequential imports will work because the parent will already have been imported? Is there a way to achieve this?

Thanks!

**Comment by sglebs** [comment]
A good enough workaround would be to have the export sort by a computed property:

```
    def nesting_levels(self, item):
        result = 0
        current = item
        while current is not None and current.system is not None:
            result += 1
            current = current.system
        return result
```

But I don't want to have this property in the Admin GUI because I don't want to make things slow. Besides, it can't be sorted by this column in the admin GUI - Django won't let me sort by a non-persistent property.

**Comment by bmihelac** [comment]
One solution could be to override [before_import](https://django-import-export.readthedocs.org/en/latest/api_resources.html#import_export.resources.Resource.before_import) and sort dataset as needed before actual import. 

Please reopen if needed
