### ISSUE TITLE
Import/Export stopped working with Django 1.10

### ISSUE THREAD

**Issue by debugger22** [django-import-export/django-import-export#529]
> The current_app parameter for the following function and classes is removed:
> django.shortcuts.render()
> django.template.Context()
> django.template.RequestContext()
> django.template.response.TemplateResponse()

c.f. [Django 1.10 release notes](https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10)

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/import_export/admin.py", line 369, in export_action
    context, current_app=self.admin_site.name)
TypeError: __init__() got an unexpected keyword argument 'current_app'
```

**Comment by mgrdcm** [comment]
I'm using `django-import-export==0.5.1` with `Django==1.10.5` and have had no problems.

**Comment by manelclos** [comment]
Closing inactive ticket. Please reopen if necessary.
