### ISSUE TITLE
Error 'Enter a valid date'

### ISSUE THREAD

**Issue by xingkongnangua** [django-import-export/django-import-export#558]
My excel file record like this:
user	dump_type	cur_date	cur_time
SY-R-GIB1	TSV_TNEW_PAGE_ALLOC_FAILED	12/21/2016	10:35:29
ZHANG279	LOAD_PROGRAM_NOT_FOUND	12/21/2016	20:02:41

When I want to import excel file, error occur. And I see the format of date had changed.
Line number: 1 - Column 'cur_date': Enter a valid date.
SY-R-GIB1, TSV_TNEW_PAGE_ALLOC_FAILED, 42725.0, 0.44130787037
Traceback (most recent call last):
File "build\bdist.win32\egg\import_export\resources.py", line 434, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "build\bdist.win32\egg\import_export\resources.py", line 258, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "build\bdist.win32\egg\import_export\resources.py", line 252, in get_instance
return instance_loader.get_instance(row)
File "build\bdist.win32\egg\import_export\instance_loaders.py", line 32, in get_instance
params[field.attribute] = field.clean(row)
File "build\bdist.win32\egg\import_export\fields.py", line 68, in clean
raise ValueError("Column '%s': %s" % (self.column_name, e))
ValueError: Column 'cur_date': Enter a valid date.

Part of DumpResource :
class DumpResource(resources.ModelResource):
    cur_date = fields.Field(column_name='cur_date',widget=DateWidget(format='%m/%d/%Y'))

What should I do to solve this problem?

**Comment by lilaLeon** [comment]
This could be an Excel-Error. Try forcing text-format on the datecolumn. 42725 is 12/21/2016 in excels dateformat. Hope this helps.
