### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused :(

### ISSUE THREAD

**Issue by 10featj** [django-import-export/django-import-export#584]
`Traceback (most recent call last):
File "/home/vagrant/env/local/lib/python2.7/site-packages/import_export/resources.py", line 457, in import_row
self.save_instance(instance, using_transactions, dry_run)
File "/home/vagrant/env/local/lib/python2.7/site-packages/import_export/resources.py", line 276, in save_instance
instance.save()
File "/vagrant/twm/component/models.py", line 174, in save
return super(Component, self).save(*args, **kwargs)
File "/home/vagrant/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
force_update=force_update, update_fields=update_fields)
File "/home/vagrant/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
update_fields=update_fields, raw=raw, using=using)
File "/home/vagrant/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
response = receiver(signal=self, sender=sender, **named)
File "/home/vagrant/env/local/lib/python2.7/site-packages/haystack/signals.py", line 52, in handle_save
index.update_object(instance, using=using)
File "/home/vagrant/env/local/lib/python2.7/site-packages/haystack/indexes.py", line 282, in update_object
backend.update(self, [instance])
File "/home/vagrant/env/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 193, in update
bulk(self.conn, prepped_docs, index=self.index_name, doc_type='modelresult')
File "/home/vagrant/env/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 188, in bulk
for ok, item in streaming_bulk(client, actions, **kwargs):
File "/home/vagrant/env/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 160, in streaming_bulk
for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
File "/home/vagrant/env/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 89, in _process_bulk_chunk
raise e
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f7f0225fa10>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f7f0225fa10>: Failed to establish a new connection: [Errno 111] Connection refused)`

I'm getting this error when I’m trying to import a new record, Any help would be appreciated :)

**Comment by gthieleb** [comment]
This error seems not related to django-import-export. Looks like something wrong with elastic search backends.
