### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by gamabounty** [django-import-export/django-import-export#606]
I am trying to import a xls file using the import button in the Django admin and got this error for each line, that I cannot resolve : 

```
Traceback (most recent call last):
File "/Users/etienne/GIT/azerty/venv/lib/python2.7/site-packages/import_export/resources.py", line 441, in import_row
original = deepcopy(instance)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
y = _reconstruct(x, rv, 1, memo)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 334, in _reconstruct
state = deepcopy(state, memo)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
y = copier(x, memo)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 256, in _deepcopy_dict
for key, value in x.iteritems():
RuntimeError: dictionary changed size during iteration
```

Even with a file itself exported by django-import-export, it does not work when trying to import it right after (no matter the extension ...).

Has anyone encountered it ? Any help would be deeply appreciated on this issue.

**Comment by xPapp** [comment]
+1

**Comment by xPapp** [comment]
created merge request https://github.com/django-import-export/django-import-export/pull/617
