### ISSUE TITLE
Model with UUID primary key: exception on export to xls

### ISSUE THREAD

**Issue by architux** [django-import-export/django-import-export#754]
I've tried to export some rows from the model containing UUID field as primary key to various supported file formats. Export to `csv`, `ods`, `tsv`, `html` seem to work fine, but other formats (`xls`, `xlsx`, `json`, `yaml`) throw some exceptions during export.

There's an exception during export to `xls` file:
```
2018-03-05 07:42:05 [ERROR] exception.py:exception:135  Internal Server Error: /simsim/order/order/export/
Traceback (most recent call last):
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/tablib/formats/_xls.py", line 133, in dset_sheet
    if '\n' in col:
TypeError: argument of type 'UUID' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/admin.py", line 402, in export_action
    export_data = self.get_export_data(file_format, queryset, request=request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/admin.py", line 384, in get_export_data
    export_data = file_format.export_data(data)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/formats/base_formats.py", line 109, in export_data
    return self.get_format().export_set(dataset, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/tablib/formats/_xls.py", line 47, in export_set
    dset_sheet(dataset, ws)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/tablib/formats/_xls.py", line 138, in dset_sheet
    ws.write(i, j, col)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/xlwt/Worksheet.py", line 1088, in write
    self.row(r).write(c, label, style)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/xlwt/Row.py", line 254, in write
    raise Exception("Unexpected data type %r" % type(label))
Exception: Unexpected data type <class 'uuid.UUID'>
```
Ubuntu 16.04.4 LTS
Python 3.5.2
Django 1.11.10
tablib 0.12.1
django-import-export 1.0.0

**Comment by GregKaleka** [comment]
Please share your code.

**Comment by nikhil0162** [comment]
Has anyone solved this issue....

**Comment by fabianallendorf** [comment]
I recently ran into the same issue when exporting as `xls`. Does anybody know why this happens?

**Comment by keomabrun** [comment]
Hi @andrewgy8 @GregKaleka could it be possible to re-open this issue ?

I am facing the same issue. I am using: 
- django-import-export v3.0.1
- tablib v3.2.1

Here is how I declare my resource:

```
class WaitingRequestResource(resources.ModelResource):

    class Meta:
        model = WaitingRequest
        skip_unchanged = True
        report_skipped = False

        fields = (
            "period", "status",
            "user", "user__first_name", "user__last_name", "user__id_external", "boat__name", "port__name",
            "date_created", "date_modified", "id",
        )
        export_order = fields
```
`user` is an object
`id` is a uuid
the rest are stings

Let me know if you need more code.
Thanks !

**Comment by matthewhegarty** [comment]
I've re-opened, but this looks like it could be an upstream issue with tablib (which itself depends on deprecated package xlwt).

**Comment by matthewhegarty** [comment]
Can you export as xlsx (not xls)?  This uses a different implementation (openpyxl) and therefore may not hit the issue above.

**Comment by keomabrun** [comment]
Thank you @matthewhegarty ! 
It indeed works perfectly when using xlsx.

**Comment by matthewhegarty** [comment]
Closing.  xlsx should be used in favour of xls.
