### ISSUE TITLE
Model with UUID primary key: exception on export to json

### ISSUE THREAD

**Issue by vmm86** [django-import-export/django-import-export#756]
I've tried to export some rows from the model containing UUID field as primary key to various supported file formats. Export to `csv`, `ods`, `tsv`, `html` seem to work fine, but other formats (`xls`, `xlsx`, `json`, `yaml`) throw some exceptions during export.

There's an exception during export to `json` file:
```
2018-03-05 08:11:48 [ERROR] exception.py:exception:135  Internal Server Error: /simsim/order/order/export/
Traceback (most recent call last):
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/admin.py", line 402, in export_action
    export_data = self.get_export_data(file_format, queryset, request=request)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/admin.py", line 384, in get_export_data
    export_data = file_format.export_data(data)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/import_export/formats/base_formats.py", line 109, in export_data
    return self.get_format().export_set(dataset, **kwargs)
  File "/home/vmm/www/belcanto/!.bezantrakta-django/venv/lib/python3.5/site-packages/tablib/formats/_json.py", line 30, in export_set
    return json.dumps(dataset.dict, default=date_handler)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```
Ubuntu 16.04.4 LTS
Python 3.5.2
Django 1.11.10
tablib 0.12.1
django-import-export 1.0.0

**Comment by omidraha** [comment]
What is your code for this error?
