### ISSUE TITLE
Unable to import with UUID `id`

### ISSUE THREAD

**Issue by anuj9196** [django-import-export/django-import-export#783]
```
Django: 2.0
django-import-export: 1.0.1
tablib: 0.12.1
```
**app/models.py**
```
class ChapterQuestion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    word = models.CharField(max_length=250)
    definition = models.CharField(max_length=250)
    pronunciation = models.CharField(max_length=250, blank=True)
    synonym = models.CharField(max_length=250, blank=True)
    antonym = models.CharField(max_length=250, blank=True)
    comment = models.CharField(max_length=250, blank=True, null=True)
```
**app/admin.py**
```
class ChapterQuestionResource(resources.ModelResource):
    class Meta:
        model = ChapterQuestion
        fields = (
            'chapter__course__name', 'chapter__name', 'word', 'definition',
            'synonym', 'antonym', 'pronunciation', 'comment'
        )


@admin.register(ChapterQuestion)
class ChapterQuestionAdmin(ImportExportModelAdmin):
    resource_class = ChapterQuestionResource

    exclude = ['created_by']
    list_display = ['word', 'definition', 'chapter', 'get_chapter_course', 'created_by']
```

But, when I import `.xls` file, it gives error as ([sample file](https://file.io/ATR0iW))

```
Errors

    Line number: 1 - 'id'
    Hello, world, , , , , Test course 001, Chapter 001

    Traceback (most recent call last):
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/resources.py", line 453, in import_row
    instance, new = self.get_or_init_instance(instance_loader, row)
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/resources.py", line 267, in get_or_init_instance
    instance = self.get_instance(instance_loader, row)
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/resources.py", line 261, in get_instance
    return instance_loader.get_instance(row)
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/instance_loaders.py", line 31, in get_instance
    field = self.resource.fields[key]
    KeyError: 'id'
    Line number: 2 - 'id'
    hello, world, , this it, that thing, commets are welcome, Test course 001, Chapter 001

    Traceback (most recent call last):
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/resources.py", line 453, in import_row
    instance, new = self.get_or_init_instance(instance_loader, row)
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/resources.py", line 267, in get_or_init_instance
    instance = self.get_instance(instance_loader, row)
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/resources.py", line 261, in get_instance
    return instance_loader.get_instance(row)
    File "/Users/anuj/.local/share/virtualenvs/django-vocab-899c1OSV/lib/python3.6/site-packages/import_export/instance_loaders.py", line 31, in get_instance
    field = self.resource.fields[key]
    KeyError: 'id'
```

**Comment by bdallard** [comment]
You need to create your class in model.py then import it in a new file resources.py and finaly import both of them in admin.py ! 
Look at the last comment  : https://stackoverflow.com/questions/30512150/django-import-export-line-number-1-ucolumn-id-not-found

**Comment by anuj9196** [comment]
@bdallard If you see my question, I have already defined specific classes in their respective files. If something I'm missing, which class you are talking about to define.

I tried with answers from your reference StackOverflow question by including `id` in the resources fields list but it didn't work. I tried by adding `exclude = ('id',)` even it does not work.

**Comment by rarjpg** [comment]
Bump, I can't import UUID `id` field too. The importer does not even recognize it: when I do not use default on the field and use `null=False` it says `NOT NULL` constraint failed.

**Comment by cjhunter421** [comment]
Hey, @anuj9196 - Did you ever find a way to make this work or is importing with a UUID not compatible with the django import-export library?

**Comment by matthewhegarty** [comment]
It should be supported.  Please raise a new issue if you are having issues. I recommend testing with the v3.0 beta (available on pypi)

**Comment by cjhunter421** [comment]
@matthewhegarty Thank you for the quick reply - I'll test some more with v3.0 - I'm fairly confident that I'm doing something wrong and that it's not an issue with the package, just need to trace what. Will open an issue if I don't resolve. Error is no longer the same as this thread anyway - 

> NON FIELD SPECIFIC
> “” is not a valid UUID.
