### ISSUE TITLE
Importing and OneToOne relationship

### ISSUE THREAD

**Issue by mahadi** [django-import-export/django-import-export#792]
Hi, i am using the following structure for my project and i am struggling with importing data from a xlsx sheet:

```python
# models.py

class MotorType(models.Model):
    """ Represents a motor type"""
    name = models.CharField(max_length=200)

class MotorStaff(models.Model):
    """ Extends the django user model by a separate model relationship which holds additional user
    attributes
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # by default a new user is not a staff member which take care of the motor administration
    is_motor_staff = models.BooleanField(default=False)

    def __str__(self):
        return u"{}".format(self.user.username)

class Motor(models.Model):
    """ Represent a single motor instance """
    motor_type = models.ForeignKey(MotorType, on_delete=models.CASCADE, default=None)
    internal_id = models.CharField(max_length=200)
    date_of_receipt = models.DateField(help_text="""Date at which the motor was received""")
    responsible_person = models.ForeignKey(MotorStaff,
                                           on_delete=models.SET_NULL,
                                           default=None,
                                           blank=True,
                                           null=True,
                                           limit_choices_to={'is_motor_staff': True})


    def __str__(self):
        return u"{}".format(self.internal_id)


# resource.py

class FullNameForeignKeyWidget(ForeignKeyWidget):
    def get_queryset(self, value, row):
        objects = self.model.objects.filter(
            user__username__iexact=row["responsible_person"]
        )
        return objects

class MotorResource(resources.ModelResource):
    motor_type = fields.Field(
        column_name='motor_type',
        attribute='motor_type',
        widget=ForeignKeyWidget(MotorType, 'name')
    )

    responsible_person = fields.Field(
        column_name='responsible_person',
        attribute='responsible_person',
        widget=FullNameForeignKeyWidget(MotorStaff)
    )

    class Meta:
        model = Motor
        skip_unchanged = True
        report_skipped = True
        raise_errors = True
        import_id_fields = ('internal_id',)
        exclude = ('id', )
```

The identification of `motor_type` works without any problems. But trying to identify the final user using the `responsible_person` column and a string of 'test_user' still gives:

`Line number: 1 - Column 'responsible_person': invalid literal for int() with base 10: 'test_user' `

When debugging i can see that the correct user object is found in the `get_queryset` method of `FullNameForeignKeyWidget` as a QuerySet with one element.

If i change the widget to
```widget=FullNameForeignKeyWidget(MotorStaff, 'user__username')```
the objects is found and gets passed on. But this finally throws:

```
Line number: 1 - 'MotorStaff' object has no attribute 'user__username'

Traceback (most recent call last):
File "...lib\site-packages\import_export\resources.py", line 477, in import_row
diff.compare_with(self, instance, dry_run)
File "...lib\site-packages\import_export\resources.py", line 170, in compare_with
self.right = self._export_resource_fields(resource, instance)
File "...lib\site-packages\import_export\resources.py", line 186, in _export_resource_fields
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "...lib\site-packages\import_export\resources.py", line 186, in <listcomp>
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "...lib\site-packages\import_export\resources.py", line 615, in export_field
return field.export(obj)
File "...lib\site-packages\import_export\fields.py", line 132, in export
return self.widget.render(value, obj)
File "...lib\site-packages\import_export\widgets.py", line 346, in render
return getattr(value, self.field)
AttributeError: 'MotorStaff' object has no attribute 'user__username'
```

Any ideas how i could succeed here?

django-import-export version used is: 1.0.1

**Comment by mahadi** [comment]
I solved it using the following dehydrate method:

```
class MotorResource(resources.ModelResource):
...
    def dehydrate_responsible_person(self, motor):
        if motor.responsible_person is not None:
            return "%s" % motor.responsible_person.user.username
        else:
            None
```
