### ISSUE TITLE
Exporting empty field when using ForeignKeyWidget

### ISSUE THREAD

**Issue by AndreGuerra123** [django-import-export/django-import-export#849]
Hello,
I'm trying to export a foreign key property however remains empty in the exported excel file.

resources.py
```
class VariableResource(resources.ModelResource):    
    process = fields.Field(attribute="process",column_name='process',widget=ForeignKeyWidget(models.Process,'name'))
    batch = fields.Field(attribute="batch",column_name='batch',widget=ForeignKeyWidget(models.Batch, 'name'))  
    timestamp = fields.Field(attribute='timestamp',column_name='timestamp',widget=DateTimeWidget()) 

    class Meta:
        model = models.Variable
        skip_unchanged = True
        report_skipped = True
        exclude = ('id','created','modified')
        import_id_fields = ('timestamp','batch','name')
        export_order = ('timestamp','process','batch','name','value')

    def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        user = kwargs['user']
        for row in dataset.dict:
            process=models.Process.objects.filter(name=row['process'],owner=user).first()
            if not process:
                raise ValidationError('Could not find process \'%s\' for user \'%s\' defined in row %s.' % (process,user,row))
            else:
                batch=models.Batch.objects.filter(name=row['batch'],process=process).first()
                if not batch:
                    raise ValidationError('Could not find batch \'%s\' related to process \'%s\' for user \'%s\' for row %s' % (batch,process,user,row))

```
using this configuration I can import properly. However, as I said, I cannot export the process related to that batch. If I replace process by process__name in the attribute of field process I can export but cannot import, giving me the following error:

```
Line number: 1 - 'NoneType' object has no attribute 'name'
2018-10-22 15:04:48, ProcessOne, BatchOne, asasa, 2.0

Traceback (most recent call last):
File "/home/guerra/.local/share/virtualenvs/biopy-ngJchh-Q/lib/python3.6/site-packages/import_export/resources.py", line 471, in import_row
self.import_obj(instance, row, dry_run)
File "/home/guerra/.local/share/virtualenvs/biopy-ngJchh-Q/lib/python3.6/site-packages/import_export/resources.py", line 343, in import_obj
self.import_field(field, obj, data)
File "/home/guerra/.local/share/virtualenvs/biopy-ngJchh-Q/lib/python3.6/site-packages/import_export/resources.py", line 330, in import_field
field.save(obj, data, is_m2m)
File "/home/guerra/.local/share/virtualenvs/biopy-ngJchh-Q/lib/python3.6/site-packages/import_export/fields.py", line 120, in save
setattr(obj, attrs[-1], cleaned)
AttributeError: 'NoneType' object has no attribute 'name' 
```

**Comment by AndreGuerra123** [comment]
Solution:

```
class VariableResource(resources.ModelResource):    
    process = fields.Field(attribute="batch__process",column_name='process',widget=ForeignKeyWidget(models.Process,'name'))
    batch = fields.Field(attribute="batch",column_name='batch',widget=ForeignKeyWidget(models.Batch, 'name'))  

    class Meta:
        model = models.Variable
        fields = ('timestamp','batch','name','value') # Declare which field from model to use.
        skip_unchanged = True
        report_skipped = True
        import_id_fields = ('timestamp','batch','name','value')
        export_order = ('timestamp','process','batch','name','value')
```
I leave it here for future reference. Closing.
