### ISSUE TITLE
Retrieving logged user inside resource class

### ISSUE THREAD

**Issue by AndreGuerra123** [django-import-export/django-import-export#850]
Hello,
As the title says, I would like to retrieve the user logged in the Resource class.
Currently, I achieve that by declaring:
`user=kwargs['user']`
However, this solution only works in the admin view (ImportExportModelAdmin). 
When I make the public generic view it outputs an kwargs key error:

```
Traceback (most recent call last):
File "/home/guerra/.local/share/virtualenvs/biopy-ngJchh-Q/lib/python3.6/site-packages/import_export/resources.py", line 541, in import_data_inner
self.before_import(dataset, using_transactions, dry_run, **kwargs)
File "/home/guerra/Desktop/biopy/BioPyApp/resources.py", line 57, in before_import
user = kwargs['user']
KeyError: 'user'
```

Inside Resource:

```
def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        user = kwargs['user']
        if not user.is_superuser:
            for row in dataset.dict:
                process=models.Process.objects.filter(name=row['process'],owner=user).first()
                if not process:
                    raise ValidationError('Could not find process \'%s\' for user \'%s\' defined in row %s.' % (process,user,row))
                else:
                    batch=models.Batch.objects.filter(name=row['batch'],process=process).first()
                    if not batch:
                        raise ValidationError('Could not find batch \'%s\' related to process \'%s\' for user \'%s\' for row %s' % (batch,process,user,row))
```
My view:

```
@method_decorator(login_required,name='dispatch')
class VariableFileImport(generic.View):
    from_encoding = "utf-8"
    formats = (
        base_formats.CSV,
        base_formats.XLS,
        base_formats.TSV,
        base_formats.ODS,
        base_formats.JSON,
        base_formats.YAML,
        base_formats.HTML,
    )
    import_template_name = 'actions/acquisition/import/variable_file_import.html'
    resource = VariableResource()

    def get_import_formats(self):
        """
        Returns available import formats.
        """
        return [f for f in self.formats if f().can_import()]

    def get(self, *args, **kwargs ):
        '''
        Perform a dry_run of the import to make sure the import will not
        result in errors.  If there where no error, save the user
        uploaded file to a local temp file that will be used by
        'process_import' for the actual import.
        '''
        context = {}

        import_formats = self.get_import_formats()
        form = ImportForm(import_formats,
                          self.request.POST or None,
                          self.request.FILES or None)

        if self.request.POST and form.is_valid():
            input_format = import_formats[
                int(form.cleaned_data['input_format'])
            ]()
            import_file = form.cleaned_data['import_file']
            # first always write the uploaded file to disk as it may be a
            # memory file or else based on settings upload handlers
            with tempfile.NamedTemporaryFile(delete=False) as uploaded_file:
                for chunk in import_file.chunks():
                    uploaded_file.write(chunk)

            # then read the file, using the proper format-specific mode
            with open(uploaded_file.name,
                      input_format.get_read_mode()) as uploaded_import_file:
                # warning, big files may exceed memory
                data = uploaded_import_file.read()
                if not input_format.is_binary() and self.from_encoding:
                    data = force_text(data, self.from_encoding)
                dataset = input_format.create_dataset(data)
                result = self.resource.import_data(dataset, dry_run=True,
                                              raise_errors=False)

            context['result'] = result

            if not result.has_errors():
                context['confirm_form'] = ConfirmImportForm(initial={
                    'import_file_name': os.path.basename(uploaded_file.name),
                    'input_format': form.cleaned_data['input_format'],
                })

        context['form'] = form
        context['fields'] = [f.column_name for f in self.resource.get_fields()]

        return TemplateResponse(self.request, [self.import_template_name], context)

    def post(self, *args, **kwargs ):
        '''
        Perform a dry_run of the import to make sure the import will not
        result in errors.  If there where no error, save the user
        uploaded file to a local temp file that will be used by
        'process_import' for the actual import.
        '''
        context = {}
        import_formats = self.get_import_formats()
        form = ImportForm(import_formats,
                          self.request.POST or None,
                          self.request.FILES or None)

        if self.request.POST and form.is_valid():
            input_format = import_formats[
                int(form.cleaned_data['input_format'])
            ]()
            import_file = form.cleaned_data['import_file']
            # first always write the uploaded file to disk as it may be a
            # memory file or else based on settings upload handlers
            with tempfile.NamedTemporaryFile(delete=False) as uploaded_file:
                for chunk in import_file.chunks():
                    uploaded_file.write(chunk)

            # then read the file, using the proper format-specific mode
            with open(uploaded_file.name,
                      input_format.get_read_mode()) as uploaded_import_file:
                # warning, big files may exceed memory
                data = uploaded_import_file.read()
                if not input_format.is_binary() and self.from_encoding:
                    data = force_text(data, self.from_encoding)
                dataset = input_format.create_dataset(data)
                result = self.resource.import_data(dataset, dry_run=True,
                                              raise_errors=False)

            context['result'] = result

            if not result.has_errors():
                context['confirm_form'] = ConfirmImportForm(initial={
                    'import_file_name': os.path.basename(uploaded_file.name),
                    'input_format': form.cleaned_data['input_format'],
                })

        context['form'] = form
        context['fields'] = [f.column_name for f in self.resource.get_fields()]

        return TemplateResponse(self.request, [self.import_template_name], context)
```

**Comment by senabIsShort** [comment]
I'm posting for future users, this is how I saved the logged in user.

**view.py**
``` Python
class ImportData(LoginRequiredMixin, TemplateView):
    template_name = 'reglements/import_data.html'
    using_resource = None

    def post(self, request):
        resource = self.using_resource
        dataset = Dataset()
        new_data = request.FILES['importfile']

        imported_data = dataset.load(new_data.read())
        result = resource.import_data(dataset, dry_run=True, current_user=request.user, raise_errors=True)  
        # Note here the "current_user=request.user" as kwarg to be passed down

        if not result.has_errors():
            resource.import_data(dataset, dry_run=False, current_user=request.user)  
            # Don't forget to pass request user on the real import like I did !
            messages.success(request, 'Import de données réussi !')
        else:
            messages.error(request, "Erreur lors de l'import des données.")
        return redirect('reglements:list')
```

**resources.py**
``` Python
class PaiementResource(resources.ModelResource):
    def after_import_instance(self, instance, new, **kwargs):
        instance.staff = kwargs['current_user']

    class Meta:
        model = Paiement
        import_id_fields = ('adherent', 'motif',)
        fields = ('adherent', 'motif', 'methode', 'date_paiement', 'montant',)
```

The Resource code above is obviously very specific to my project, but please note :
* I'm simply adding the relevant info to the instance using the `after_import_instance` hook and our custom `current_user` kwarg ;
* The relevant field (in my case, it's called `staff`, but it's really just the typical 'saved_by' field you might have) is **not** declared as one of the fields to be imported (who would want to add an empty column just for the header ?)

Hopefully this can help people who stumble upon it!
