### ISSUE TITLE
Using the importer directly from tablib (primary key not generated automatically) 

### ISSUE THREAD

**Issue by AndreGuerra123** [django-import-export/django-import-export#874]
Hello,
I'm trying to use your importer to import dedicated data from a historian server.
The data is not stored in a file but in a unknown database. I can retrieve the data using the necessary drivers and build a tablib dataset as follows:

```
data = tablib.Dataset()
data.headers = ('process','batch','name','timestamp','value')
```

...then I append the data to dataset:

```
data.append((process.name,batch.name,node.name,row.SourceTimestamp.replace(tzinfo=timezone.utc),float(row.Value.Value)))
```

My resource classes are defined as:

```
class ProcessBatchResource(resources.ModelResource):
    process = fields.Field(column_name='process',widget=CharWidget())
    batch = fields.Field(attribute="batch",column_name='batch',widget=ProcessBatchForeignKeyWidget(Batch, 'name'))  

    def dehydrate_process(self,Instance):
        return rgetattr(Instance,'batch.process.name')
        
    def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        for row in dataset.dict:
            process_ins=Process.objects.filter(name=row['process'],owner=self.user).first()
            if not process_ins:
                raise ValidationError('Could not find process \'%s\' for user \'%s\' defined in row %s.' % (process_ins,self.user,row))
            batch_ins=Batch.objects.filter(name=row['batch'],process=process_ins).first()
            if not batch_ins:
                raise ValidationError('Could not find batch \'%s\' related to process \'%s\' for user \'%s\' for row %s' % (batch_ins,process_ins,self.user,row))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

class VariableResource(ProcessBatchResource):    
    class Meta:        
        model = Variable
        skip_unchanged = True
        report_skipped = True
        exclude = ('id','created','modified')
        import_id_fields = ('batch','name','timestamp') 
        export_order = ('timestamp','process','batch','name','value')

    def get_queryset(self):
        if not self.user.is_superuser:
            return Variable.objects.filter(batch__process__owner=self.user)
        else:
            return Variable.objects.all()
```

and my model as:

```
class Variable(models.Model):
    batch = models.ForeignKey('Batch',on_delete=models.CASCADE,related_name="variable_batch")
    name = models.CharField(max_length=25)
    timestamp = models.DateTimeField()
    value = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    elapsed = computed_property.ComputedFloatField(compute_from='get_elapsed',blank=True,null=True)
    
    def get_elapsed(self):
        return deltaEpoch(self.timestamp,self.batch.start)

    class Meta:
        unique_together=('batch','name','timestamp')
    
    objects = DataFrameManager()

    def __str__(self):
        return " : ".join([str(self.id), self.batch.process.name, self.batch.name, self.name, str(self.value), self.timestamp.replace(microsecond=0).isoformat(), self.modified.replace(microsecond=0).isoformat(' ')])
```

When I import using an excel file for instance, everything works fine. It seems that when tablib dataset is used It doesn't generate primary keys automatically:

```
Traceback (most recent call last):
  File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\import_export\resources.py", line 475, in import_row
    self.save_instance(instance, using_transactions, dry_run)
  File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\import_export\resources.py", line 285, in save_instance
    instance.save()
  File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\django\db\models\base.py", line 803, in _save_table
    raise ValueError("Cannot force an update in save() with no primary key.")
ValueError: Cannot force an update in save() with no primary key.
```

Any ideias?
Best regards,

**Comment by AndreGuerra123** [comment]
I simplified the resources class code to avoid the use of the foreign key widgets.
Now in my classes I have:

```
class ProcessBatchResource(resources.ModelResource):
    processname = fields.Field(attribute="batch__process__name",column_name='process',widget=CharWidget())
    batchname = fields.Field(attribute="batch__name",column_name='batch',widget=CharWidget())  
  
    def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        for row in dataset.dict:
            process_ins=Process.objects.filter(name=row['process'],owner=self.user).first()
            if not process_ins:
                raise ValidationError('Could not find process \'%s\' for user \'%s\' defined in row %s.' % (process_ins,self.user,row))
            batch_ins=Batch.objects.filter(name=row['batch'],process=process_ins).first()
            if not batch_ins:
                raise ValidationError('Could not find batch \'%s\' related to process \'%s\' for user \'%s\' for row %s' % (batch_ins,process_ins,self.user,row))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

class VariableResource(ProcessBatchResource):    
    class Meta:        
        model = Variable
        skip_unchanged = True
        report_skipped = True
        exclude = ('id','created','modified','elapsed','batch')
        import_id_fields = ('processname','batchname','name','timestamp') 
        export_order = ('timestamp','processname','batchname','name','value')

    def get_queryset(self):
        if not self.user.is_superuser:
            return Variable.objects.filter(batch__process__owner=self.user)
        else:
            return Variable.objects.all()
```

However I'm receiving this weird error which I really cannot find the root cause.

```
Line number: 7 - 'NoneType' object has no attribute 'name'
ProcessOne, BatchOne, Expression1, 2018-11-25 19:30:39.997000+00:00, 3.731479412271068
Traceback (most recent call last):
File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\import_export\resources.py", line 471, in import_row
self.import_obj(instance, row, dry_run)
File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\import_export\resources.py", line 343, in import_obj
self.import_field(field, obj, data)
File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\import_export\resources.py", line 330, in import_field
field.save(obj, data, is_m2m)
File "C:\Users\admin\.virtualenvs\BioPy-VonJR-3F\lib\site-packages\import_export\fields.py", line 120, in save
setattr(obj, attrs[-1], cleaned)
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by yozlet** [comment]
Also, a more general tip: use a decent visual debugger and step through the relevant code while keeping an eye on variables. I'm new to Django Import/Export, and I don't think I'd have made proper progress with it if I didn't have either VSCode's Python debugger or [pudb](https://documen.tician.de/pudb/index.html)
