### ISSUE TITLE
Noisy admin log -Exception while resolving variable 'non_field_errors' in template 'admin/import_export/change_list_import_export.html'.

### ISSUE THREAD

**Issue by daino3** [django-import-export/django-import-export#936]
I might've set my admin/models up incorrectly, but my logs are unbearably noisy after adding this package to my project.

```text
Traceback (most recent call last):
  File "/opt/spoton_venvs/salons/lib/python3.6/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in None
[Tue 2019-04-02 20:03:52+0000] DEBUG [django.template._resolve_lookup:878] Exception while resolving variable 'non_field_errors' in template 'admin/import_export/change_list_import_export.html'.
Traceback (most recent call last):
  File "/opt/spoton_venvs/salons/lib/python3.6/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spoton_venvs/salons/lib/python3.6/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'
```

How do I quiet these down?

**Comment by reedjones** [comment]
currently have the same problem

**Comment by matthewhegarty** [comment]
Hi Reed

What version are you using?  I suggest use the [v4 beta](https://github.com/django-import-export/django-import-export/releases/tag/4.0.0-beta.2) version (if not already) as this has the most recent fixes.

This is an old issue, can you be more specific about the exact issue you are seeing?

Any help to resolve is much appreciated.
