### ISSUE TITLE
xls data cell format

### ISSUE THREAD

**Issue by sprenge** [django-import-export/django-import-export#96]
I have the impression that for xls import the data cell format must be a string.  I get import failures when the cell input type is for instance numeric.

**Comment by NathanQ** [comment]
@bmihelac I'm having an issue with the format as well. Here is my model with two charfields: 

```
class Coupon(models.Model):
    office_code = models.CharField(
        max_length=10,
        unique=True
        )
    online_code = models.CharField(
        max_length=10,
        unique=True
        )

    class Meta:
        verbose_name = 'Coupon Pair'
        verbose_name_plural = 'Coupon Pairs'

    def __unicode__(self):
        return unicode(self.id)
```

And, the admin:

```
class CouponResource(resources.ModelResource):

    class Meta:
        model = Coupon
        exclude = ('id', )
        import_id_fields = ['office_code', 'online_code', ]
        skip_unchanged = True


class CouponAdmin(ImportExportModelAdmin):

    resource_class = CouponResource

    class Meta:
        model = Coupon
        list_per_page = 20
```

On a test import, if a column, say office_code, only contains numbers, the importer will add a '.0' on the end of each. In the excel file, I've tried using the format tool to format as text, but this didn't help. How do I go about saving without adding the periods and zeros? 

Thanks a lot for the helpful plugin!

**Comment by sassanh** [comment]
@bmihelac any updates on this? I'm getting `ValueError: invalid literal for int() with base 10: ''` as well:

```
Traceback (most recent call last):
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/import_export/resources.py", line 408, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/import_export/resources.py", line 232, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/import_export/resources.py", line 226, in get_instance
return instance_loader.get_instance(row)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/import_export/instance_loaders.py", line 33, in get_instance
return self.get_queryset().get(**params)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/query.py", line 378, in get
clone = self.filter(*args, **kwargs)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/query.py", line 790, in filter
return self._filter_or_exclude(False, *args, **kwargs)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/query.py", line 808, in _filter_or_exclude
clone.query.add_q(Q(*args, **kwargs))
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1243, in add_q
clause, _ = self._add_q(q_object, self.used_aliases)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1269, in _add_q
allow_joins=allow_joins, split_subq=split_subq,
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1203, in build_filter
condition = self.build_lookup(lookups, col, value)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1099, in build_lookup
return final_lookup(lhs, rhs)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/lookups.py", line 19, in __init__
self.rhs = self.get_prep_lookup()
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/lookups.py", line 57, in get_prep_lookup
return self.lhs.output_field.get_prep_lookup(self.lookup_name, self.rhs)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 744, in get_prep_lookup
return self.get_prep_value(value)
File "/Users/sassanharadji/.virtualenvs/mhelli/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 976, in get_prep_value
return int(value)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by sassanh** [comment]
It doesn't happen with `xlsx`, just happens with `xls`.

**Comment by bcanyelles** [comment]
I fixed it with overriding `clean` method of `CharWidget`:

```python
class CharWidget(widgets.CharWidget):

    def clean(self, value, row=None, *args, **kwargs):
        if isinstance(value, float):
            value = int(value)
            return "{}".format(value)
        return value
```

**Comment by walterliang** [comment]
i have the same issue:

Traceback (most recent call last):
File "C:\Users\water\Envs\CMS\lib\site-packages\import_export\resources.py", line 471, in import_row
self.import_obj(instance, row, dry_run)
File "C:\Users\water\Envs\CMS\lib\site-packages\import_export\resources.py", line 343, in import_obj
self.import_field(field, obj, data)
File "C:\Users\water\Envs\CMS\lib\site-packages\import_export\resources.py", line 330, in import_field
field.save(obj, data, is_m2m)
File "C:\Users\water\Envs\CMS\lib\site-packages\import_export\fields.py", line 115, in save
cleaned = self.clean(data)
File "C:\Users\water\Envs\CMS\lib\site-packages\import_export\fields.py", line 71, in clean
raise ValueError("Column '%s': %s" % (self.column_name, e))
ValueError: Column 'project': invalid literal for int() with base 10: '底层链1.0'

**Comment by andrewgy8** [comment]
@walterliang Did you try the fix that was submitted by @bcanyelles ?
