### ISSUE TITLE
RemovedInDjango19Warning when running manage.py migrate

### ISSUE THREAD

**Issue by pancho-villa** [django-import-export/django-import-export#98]
I'm running python 3.3 and django 1.7 and I get this error setting up a mysql db for the first time. I see it's only a warning, but I can't get the db to initialize past it. Is this an import-export error or django problem?

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/django/core/management/__init__.py", line 427, in execute_from_command_line
    utility.execute()
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/django/core/management/__init__.py", line 391, in execute
    django.setup()
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/django/apps/registry.py", line 106, in populate
    app_config.import_models(all_models)
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/django/apps/config.py", line 190, in import_models
    self.models_module = import_module(models_module_name)
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/mp/d1/pdutils/dev/PPM_Project/main/core/models.py", line 7, in <module>
    from import_export import resources
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/import_export/resources.py", line 113, in <module>
    class Resource(six.with_metaclass(DeclarativeMetaclass)):
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/django/utils/six.py", line 643, in __new__
    return meta(name, bases, d)
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/import_export/resources.py", line 104, in __new__
    attrs['fields'] = SortedDict(declared_fields)
  File "/mp/d1/pdutils/dev/python3.3/lib/python3.3/site-packages/django/utils/datastructures.py", line 136, in __init__
    RemovedInDjango19Warning, stacklevel=2
django.utils.deprecation.RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.

**Comment by manelclos** [comment]
This was fixed in 0.2.6 release: https://github.com/django-import-export/django-import-export/blob/5668de69d1c7bcc77475148401dc9c0cf2671b0c/docs/changelog.rst#026-2014-10-09

Closing.
