### ISSUE TITLE
KeyError: 'n' while importing CSV

### ISSUE THREAD

**Issue by Bhupesh-V** [django-import-export/django-import-export#986]
The issue sounds similar to the u'id' problem but it's behaving differently .
I have the following resource
```python
class TagResource(resources.ModelResource):
    class Meta:
    	model = tag
    	exclude = ('id',)
    	export_order = ('name', 'description', 'created_date')
    	import_id_fields = ('name')
```
And I am importing the stuff like this
```csv
id,name,description
,go,The GoLang Programming Language
```
The following error is generated
```bash
Line number: 1 - 'n'
go, The GoLang Programming Language

Traceback (most recent call last):
File "/home/bhupesh/Desktop/tutorialdb-test/lib/python3.6/site-packages/import_export/resources.py", line 492, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "/home/bhupesh/Desktop/tutorialdb-test/lib/python3.6/site-packages/import_export/resources.py", line 269, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "/home/bhupesh/Desktop/tutorialdb-test/lib/python3.6/site-packages/import_export/resources.py", line 263, in get_instance
return instance_loader.get_instance(row)
File "/home/bhupesh/Desktop/tutorialdb-test/lib/python3.6/site-packages/import_export/instance_loaders.py", line 31, in get_instance
field = self.resource.fields[key]
KeyError: 'n'
```

**Comment by Bhupesh-V** [comment]
Ok I fixed it
I had to add `description` in **import_id_fields**
